# Generated by Django 3.2.4 on 2021-06-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100, unique=True)),
                ('valor', models.FloatField(help_text='Valor')),
                ('detalhe', models.CharField(max_length=500, null=True)),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
    ]
