# Generated by Django 3.2.4 on 2021-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ManyToManyField(to='clientes.Cliente'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='remedio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='remedio',
            field=models.ManyToManyField(to='remedio.Remedio'),
        ),
    ]
