# Generated by Django 3.2.4 on 2021-06-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('remedio', '0001_initial'),
        ('pedido', '0002_auto_20210613_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='remedio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='remedio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remedio.remedio'),
        ),
    ]
