# Generated by Django 3.2.4 on 2021-06-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20210613_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dataEntraga',
            field=models.DateField(null=True),
        ),
    ]
